settings:
  :address:           smtp.gmail.com
  :port:                 587
  :user_name:      fereyji@gmail.com
  :password:        angiefer
  :authentication: :plain

method: sendmail
charset: utf-8